# LAB 1: Matrix and Vector Computations in python
In this lab you will use python to study the following topics:

- How to create matrices and vectors in python.

- How to manipulate matrices in python and create matrices of special types.

- How to add matrices and multiply a vector by a matrix by python.

- Solving System of Linear Equations Using Gaussian Elimination.

- Matrix Multiplication using Different views.

# First: you should run this cell

In [1]:
# Make all numpy available via shorter 'np' prefix
import numpy as np

import sympy as sym

# Question 1 :Declaring scalars, vectors, and matrices

a) Use [numpy.array](https://numpy.org/doc/stable/reference/generated/numpy.array.html) to declare the following:

1. A scalar $s = 5$
2. A vector $v = \begin{bmatrix} 5  \\ -2 \\ 4  \\ \end{bmatrix}$
3. A matrix $A = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ 7 & 8 & 9  \\ \end{bmatrix}$
4. A matrix $B = \begin{bmatrix} 1 & 2 & 3  \\ 4 & 5 & 6 \\ \end{bmatrix}$
5. A matrix $C = \begin{bmatrix} 1 & 2   \\ 3 & 4  \\ 5 & 6   \\ \end{bmatrix}$

In [276]:
#scalar using numpy 
s = np.array(5)
print("s = ",s,"\n")
# vector using numpy 

V=np.array([[5],[-2],[4]])
print("v =  \n", V,"\n")

#matrix using numpy 
A=np.array([[1,2,3,],[4,5,6],[7,8,9]])
print("A = \n",A ,"\n")


B=np.array([[1,2,3],[4,5,6]])

print("B  = \n ",B,"\n")


C=np.array([[1,2],[3,4],[5,6]])

print("C  = \n",C,"\n")         

s =  5 

v =  
 [[ 5]
 [-2]
 [ 4]] 

A = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

B  = 
  [[1 2 3]
 [4 5 6]] 

C  = 
 [[1 2]
 [3 4]
 [5 6]] 



In [2]:
#type your code here:


s = 5

v =
 [[ 5]
 [-2]
 [ 4]]

A =
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

B =
 [[1 2 3]
 [4 5 6]]

C =
 [[1 2]
 [3 4]
 [5 6]]



In [277]:
print("type(s) = ", type(s),"\n")
print("type(V) =  ", type(V),"\n")
print("type(A) =  ", type(s),"\n")

type(s) =  <class 'numpy.ndarray'> 

type(V) =   <class 'numpy.ndarray'> 

type(A) =   <class 'numpy.ndarray'> 



b) Print the data type of $s, v,$ and $A$ using `type` command in python.

In [3]:
#type your code here:


type(s) = <class 'numpy.ndarray'>

type(v) = <class 'numpy.ndarray'>

type(A) = <class 'numpy.ndarray'>



c) Using [numpy.shape](https://numpy.org/devdocs/reference/generated/numpy.shape.html) or `A.shape` print the shape of $s, v, A, B,$ and $C$.

In [278]:
print("S.shape=", s.shape,"\n")
print("v.shape=",V.shape,"\n")
print("A.shape=",A.shape,"\n")
print("B.shape=",B.shape,"\n")
print("C.shape=",C.shape,"\n")

S.shape= () 

v.shape= (3, 1) 

A.shape= (3, 3) 

B.shape= (2, 3) 

C.shape= (3, 2) 



In [4]:
#type your code here:


s.shape = ()

v.shape = (3, 1)

A.shape = (3, 3)

B.shape = (2, 3)

C.shape = (3, 2)



d) To access a given entry in the `numpy array` put the `row number - 1` and `column number - 1` in square brackets following the array name. Ex `a32 = A[2, 1]`.
- Print the value of the third row and the second column of the matrix $A$.
- Change it to $10$.
- Print the matrix A to check the entry is changed.

In [279]:
value=A[2 , 1]
print(f" A[2 ,1] = {value}","\n")
A[2,1]=10
print("A= \n",A,"\n")

 A[2 ,1] = 8 

A= 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]] 



In [5]:
#type your code here:


A[2, 1] =  8

A =
 [[ 1  2  3]
 [ 4  5  6]
 [ 7 10  9]]



e)To access a whole row or column of a matrix, use the colon operator. For example, `A[:, [1]]` is the second column of A, while `B[[1], :]` is the second row of B.

In [34]:
second_column=A[: , [1]]
print("A[:,[1]]  = \n",second_column,"\n")
second_row=B[[1], :]
print("B[[1],:] = \n ",second_row,"\n")

A[:,[1]]  = 
 [[ 2]
 [ 5]
 [10]] 

B[[1],:] = 
  [[4 5 6]] 



In [6]:
#type your code here:


A[:, [1]] =
 [[ 2]
 [ 5]
 [10]]

B[[1], :] =
 [[4 5 6]]



f) Type each of the following commands that generate special matrices:
- `np.eye(4), np.zeros(3), np.zeros((3, 1)), np.zeros((3, 5)), np.ones((2, 3)), and np.diag([4, 5, 6, 7])`

In [36]:
# Identity matrix of size 4x4
array1 = np.eye(4)

# Array of zeros with 3 elements
array2 = np.zeros(3)

# Array of zeros with shape (3, 1)
array3 = np.zeros((3, 1))

# Array of zeros with shape (3, 5)
array4 = np.zeros((3, 5))

# Array of ones with shape (2, 3)
array5 = np.ones((2, 3))

# Diagonal matrix with diagonal elements [4, 5, 6, 7]
array6 = np.diag([4, 5, 6, 7])

# Print the arrays
print("np.eye(4)  = \n",array1,"\n")


print("np.zeros(3) = \n",array2,"\n")


print("np.zeros(3,1)  = \n",array3,"\n")


print("np.zeros(3,5)  =  \n",array4)


print("np.ones(2,3)  = \n",array5,"\n")


print("np.diag([4 5 6 7 ]) = \n",array6,"\n")


np.eye(4)  = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

np.zeros(3) = 
 [0. 0. 0.] 

np.zeros(3,1)  = 
 [[0.]
 [0.]
 [0.]] 

np.zeros(3,5)  =  
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
np.ones(2,3)  = 
 [[1. 1. 1.]
 [1. 1. 1.]] 

np.diag([4 5 6 7 ]) = 
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]] 



In [7]:
#type your code here:


np.eye(4) =
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.zeros(3) =
 [0. 0. 0.]

np.zeros(3, 1) =
 [[0.]
 [0.]
 [0.]]

np.zeros(3, 5) =
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

np.ones(2, 3) =
 [[1. 1. 1.]
 [1. 1. 1.]]

np.diag([4 5 6 7]) =
 [[4 0 0 0]
 [0 5 0 0]
 [0 0 6 0]
 [0 0 0 7]]


# Question 2. Vectors Addition, Scaling, and dot product

a) Declare vectors $v1 = \begin{bmatrix} 1  \\ 2 \\ 7  \\ 4 \\ \end{bmatrix}$ and $v2 = \begin{bmatrix} 4  \\ 3 \\ 6  \\ 8 \\ \end{bmatrix}$

- Addition: $v1 + v2$
- Subtraction: $v1 - v2$
- Scaling by a number: $3 * v1$
- Scaling by a number: $v1 / 2$

In [280]:
v1=np.array([[1],[2],[7],[4]])
v2=np.array([[4],[3],[6],[8]])
#vector addition
vector_add=v1 + v2
#vector subtraction
vector_sub=v1 - v2
# scaling
scalar= 3
scaled_result=scalar* v1
scalar2=2
scaled2_result= v1/scalar2

print("v1 = \n",v1,"\n")
print("v2 = \n",v2,"\n")
print("v1 + v2  = \n",vector_add,"\n")
print("v1 - v2  = \n",vector_sub,"\n")
print("3 * v1  = \n",scaled_result,"\n")
print("v1 / 2  = \n",scaled2_result,"\n")






v1 = 
 [[1]
 [2]
 [7]
 [4]] 

v2 = 
 [[4]
 [3]
 [6]
 [8]] 

v1 + v2  = 
 [[ 5]
 [ 5]
 [13]
 [12]] 

v1 - v2  = 
 [[-3]
 [-1]
 [ 1]
 [-4]] 

3 * v1  = 
 [[ 3]
 [ 6]
 [21]
 [12]] 

v1 / 2  = 
 [[0.5]
 [1. ]
 [3.5]
 [2. ]] 



In [8]:
#type your code here:


v1 =
 [[1]
 [2]
 [7]
 [4]]

v2 =
 [[4]
 [3]
 [6]
 [8]]

v1 + v2 =
 [[ 5]
 [ 5]
 [13]
 [12]]

v1 - v2 =
 [[-3]
 [-1]
 [ 1]
 [-4]]

3*v1 =
 [[ 3]
 [ 6]
 [21]
 [12]]

v1/2 =
 [[0.5]
 [1. ]
 [3.5]
 [2. ]]



b) Find the dot product between the two vectors $v1$ and $v2$ using the following:

- [numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)
- [numpy.matmul](https://numpy.org/doc/stable/reference/generated/numpy.matmul.html#numpy.matmul)
- `v1.T @ v2`

In [52]:
#v1_transpose=np.transpose(v1)


# calculate dot product using numpy.dot
dot_product_dot=np.dot(v1.T,v2)
print("using numpy.dot = \n",dot_product_dot,"\n")

#calculte dot product using numpy .matmul
dot_product_matmul=np.matmul(v1.T,v2)

print("using numpy.matmaul = \n",dot_product_matmul,"\n")
 #calculte dot product using @
dot_product_at= v1.T @v2
print ("using @ = \n",dot_product_at,"\n" )

using numpy.dot = 
 [[84]] 

using numpy.matmaul = 
 [[84]] 

using @ = 
 [[84]] 



In [9]:
#type your code here:


Using numpy.dot =
 [[84]]

Using numpy.matmul =
 [[84]]

Using @ =
 [[84]]



c) Find the length of the vectors $v1$ and $v2$.
- Using [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html)
- Using the dot product and [numpy.sqrt](https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html)


In [57]:
# calculte the length using numpy.linalg.norm
length_v1_norm=np.linalg.norm(v1)
length_v2_norm=np.linalg.norm(v2)
print("length of v1 using  numpy.linalg.norm = \n",length_v1_norm,"\n")
print("length of v2 using  numpy.linalg.norm = \n",length_v2_norm,"\n")

# Calculate the length using dot product and numpy.sqrt
length_v1_dot_sqrt = np.sqrt(np.dot(v1.T, v1))
length_v2_dot_sqrt = np.sqrt(np.dot(v2.T, v2))

print("Length of v1 using dot product and numpy.sqrt = \n ", length_v1_dot_sqrt,"\n")
print("Length of v2 using dot product and numpy.sqrt = \n ", length_v2_dot_sqrt,"\n")

length of v1 using  numpy.linalg.norm = 
 8.366600265340756 

length of v2 using  numpy.linalg.norm = 
 11.180339887498949 

Length of v1 using dot product and numpy.sqrt = 
  [[8.36660027]] 

Length of v2 using dot product and numpy.sqrt = 
  [[11.18033989]] 



In [10]:
#type your code here:


length of v1 Using numpy.linalg.norm =
 8.366600265340756

length of v2 Using numpy.linalg.norm =
 11.180339887498949

length of v1 Using the dot product and numpy.sqrt =
 [[8.36660027]]

length of v2 Using the dot product and numpy.sqrt =
 [[11.18033989]]



d) Show that the vectors $u = \begin{bmatrix} 3  \\ 2 \\ -1  \\ 4 \\ \end{bmatrix}$ and $v = \begin{bmatrix} 1  \\ -1 \\ 1  \\ 0 \\ \end{bmatrix}$ are orthogonal.


In [60]:
u=np.array([[3],[2],[-1],[4]])
v=np.array([[1],[-1],[1],[0]])
v_orthogonal= np.dot(u.T,v)
print("u.T @ v = \n ",v_orthogonal,"\n")

u.T @ v = 
  [[0]] 



In [11]:
#type your code here:


u.T @ v =
 [[0]]



# Question 3. Matrix Addition and Matrix-Vector Multiplication

Declare vectors $u$ and $v$ and matrices $A$ and $B$ as following:
- $u = \begin{bmatrix} 2  \\ 7 \\ 2 \\ \end{bmatrix}$, $v = \begin{bmatrix} 8  \\ 2 \\ 4 \\ \end{bmatrix}$
- $A = \begin{bmatrix} 7 & 3 & 5  \\ 4 & 6 & 2 \\ \end{bmatrix}$, $B = \begin{bmatrix} 0 & 6 & 4  \\ 2 & 3 & 0 \\ \end{bmatrix}$

a) Calculate the following using python.

- $A+B$
- $B+A$
- $3A$
- $6B$
- $2(3B)$
- $6A+15B$
- $3(2A+5B)$
- $(3A^T)^T$

In [74]:
u=np.array([[2],[7],[2]])
v=np.array([[8],[2],[4]])

A=np.array([[7,3,5],[4,6,2]])
B=np.array([[0,6,4],[2,3,0]])
A_plus_B=A+B
B_plus_A=B+A
res_3A=3*A
res_6B=6*B
res_2_times_3B=2*(3*B)
res_6A_plus_15B=6*A+15*B
res_3_times_2A_plus_5B=3*(2*A+15*B)
res_3_A_T_T=(3*A.T).T
print("u =\n",u,"\n")
print("v =\n", v,"\n")
print("A =\n",A,"\n")
print("B =\n",B,"\n")
print("A + B = \n",A_plus_B,"\n")
print("B + A = \n",B_plus_A,"\n")
print("3A = \n",res_3A,"\n")
print("6B = \n",res_6B,"\n")
print("2(3B) = \n",res_2_times_3B,"\n")
print("6A + 15B = \n",res_6A_plus_15B,"\n")
print("3(2A + 5B) = \n",res_3_times_2A_plus_5B,"\n")
print("(3A^T)^T = \n",res_3_A_T_T,"\n")







u =
 [[2]
 [7]
 [2]] 

v =
 [[8]
 [2]
 [4]] 

A =
 [[7 3 5]
 [4 6 2]] 

B =
 [[0 6 4]
 [2 3 0]] 

A + B = 
 [[7 9 9]
 [6 9 2]] 

B + A = 
 [[7 9 9]
 [6 9 2]] 

3A = 
 [[21  9 15]
 [12 18  6]] 

6B = 
 [[ 0 36 24]
 [12 18  0]] 

2(3B) = 
 [[ 0 36 24]
 [12 18  0]] 

6A + 15B = 
 [[ 42 108  90]
 [ 54  81  12]] 

3(2A + 5B) = 
 [[ 42 288 210]
 [114 171  12]] 

(3A^T)^T = 
 [[21  9 15]
 [12 18  6]] 



In [12]:
#type your code here:


u =
 [[2]
 [7]
 [2]]

v =
 [[8]
 [2]
 [4]]

A =
 [[7 3 5]
 [4 6 2]]

B =
 [[0 6 4]
 [2 3 0]]

A + B =
 [[7 9 9]
 [6 9 2]]

B + A =
 [[7 9 9]
 [6 9 2]]

3A =
 [[21  9 15]
 [12 18  6]]

6B =
 [[ 0 36 24]
 [12 18  0]]

2(3B) =
 [[ 0 36 24]
 [12 18  0]]

6A + 15B =
 [[ 42 108  90]
 [ 54  81  12]]

3(2A + 5B) =
 [[ 42 108  90]
 [ 54  81  12]]


 (3A^T)^T = 
 [[21  9 15]
 [12 18  6]]


b) To obtain the matrix-vector product $Au$ using python, type `A @ u`. Calculate the following:

- $Au+Av$
- $A(u+v)$
- $(A+B)u$
- $Au+Bu$
- $A(3u)$
- $3A(u)$

In [77]:
result_Au_plus_Av = A@u + A @ v
result_A_u_plus_v = A @ (u + v)
result_A_plus_B_u = (A + B) @ u
result_Au_plus_Bu = A @ u + B @ u
result_A_times_3u = A @ (3 * u)
result_3A_times_u = 3 * (A @ u)

# Displaying results
print("Au + Av =")
print(result_Au_plus_Av)

print("\n A(u + v) =")
print(result_A_u_plus_v)

print("\n (A + B)u =")
print(result_A_plus_B_u)

print("\n Au + Bu =")
print(result_Au_plus_Bu)

print("\n A(3u) =")
print(result_A_times_3u)

print("\n 3(Au) = ")
print(result_3A_times_u)

Au + Av =
[[127]
 [106]]

 A(u + v) =
[[127]
 [106]]

 (A + B)u =
[[95]
 [79]]

 Au + Bu =
[[95]
 [79]]

 A(3u) =
[[135]
 [162]]

 3(Au) = 
[[135]
 [162]]


In [13]:
#type your code here:


Au + Av =
 [[127]
 [106]]

A(u + v) =
 [[127]
 [106]]

(A + B)u =
 [[95]
 [79]]

Au + Bu =
 [[95]
 [79]]

A(3u) =
 [[135]
 [162]]

3A(u) =
 [[135]
 [162]]



# Question 4. Gaussian Elimination and Reduced Row-Echelon Form

You will see a step-by-step example of the row operations that transform a matrix $A$ into its reduced row echelon form $R = rref(A)$. In this demonstration, each pivot is chosen to be the largest in its column (for numerical stability), so extra row interchanges are used. Since $rref(A)$ is uniquely determined by $A$, this does not affect the final answer.

The built in [rref](https://docs.sympy.org/latest/tutorial/matrices.html#rref) method `sympy.rref()` method just search for the method and its output to deal with the code.

#### (a) Generate and display a $3 \times 4$ matrix $A$ with random integer entries 

In [281]:
# to set a random set 

np.random.seed(42)
# (a) Generate and display a  3×4 with random integer entries 
#A = np.random.randint(0,10,size=(3,4)).astype(float)
#print(" \n A = ",A ,"\n")
 
    
    
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[3. 9. 7. 5.]
 [1. 1. 0. 8.]
 [6. 7. 0. 9.]]


In [14]:
#type your code here:
A = np.fix((10*(np.random.rand(3,4))))
print("\n A = \n", A)


 A = 
 [[8. 0. 4. 1.]
 [6. 6. 2. 7.]
 [0. 1. 6. 0.]]


- To transform $A$ into $R = rref(A)$, start with $R = A$.
- Normalize the first row of R to get R(1st row, 1st column) = 1

    - `R = A`
    - `R[0,:] = R[0, :] / R[0, 0]`

(note the use of the colon to operate on whole rows of the matrix). 

<div class="alert alert-block alert-warning">If your random matrix happens to have A(1, 1) = 0, then interchange rows to get a nonzero entry in the (1, 1) position before doing the calculation above.</div>

- Now subtract a multiple of the first row of R from the second row to make R(2, 1) = 0:

    - `R[1, :] = R[1, :] - R[1, 0] * R[0, :]`

- Repeat this procedure to make R(3, 1) = 0:

    - `R[2, :] = R[2, :] - R[2, 0] * R[0, :]`

The first column of your matrix $R$ should now be the same as the first column of $rref(A)$.

In [282]:
R=A
R[0, :] = R[0, :] / R[0, 0]
R[1, :] = R[1, :] - R[1,0] * R[0,:]
R[2, :] = R[2, :] - R[2,0] * R[0,:]
print("R = \n ",R)

R = 
  [[  1.           3.           2.33333333   1.66666667]
 [  0.          -2.          -2.33333333   6.33333333]
 [  0.         -11.         -14.          -1.        ]]


In [15]:
#type your code here:



 R = 
 [[ 1.     0.     0.5    0.125]
 [ 0.     6.    -1.     6.25 ]
 [ 0.     1.     6.     0.   ]]


#### (b)Operate on $R$ by the same method as in (a) to obtain the second column of $rref(A)$. First normalize row $2$ of $R$, then subtract multiples of row $2$ from rows $1$ and $3$ to put zeros in the (1, 2) and (3, 2) positions. Be sure to refer to the entries in your matrix symbolically as was done in part (a)

In [283]:
R[1, :] = R[1, :] /R[1,1]
R[2,:]=R[2,:]-R[2,1]*R[1,:]
R[0,:]=R[0,:]-R[1,:]*R[0,1]
print("R = \n ",R)

R = 
  [[  1.           0.          -1.16666667  11.16666667]
 [ -0.           1.           1.16666667  -3.16666667]
 [  0.           0.          -1.16666667 -35.83333333]]


In [16]:
#type your code here:



 R = 
 [[ 1.          0.          0.5         0.125     ]
 [ 0.          1.         -0.16666667  1.04166667]
 [ 0.          0.          6.16666667 -1.04166667]]


#### (c) Operate on $R$ by the same method as in (b) to obtain the third column of $rref(A)$. First normalize row $3$ of $R$, then subtract multiples of row $3$ from rows $1$ and $2$ to put zeros in the (1, 3) and (2, 3) positions.

In [284]:
R[2, :] = R[2, :] /R[2,2]
R[1,:]=R[1,:]-R[2,:]*R[1,2]
R[0,:]=R[0,:]-R[2,:]*R[0,2]
print("R = \n ",R)

R = 
  [[  1.           0.           0.          47.        ]
 [  0.           1.           0.         -39.        ]
 [ -0.          -0.           1.          30.71428571]]


In [17]:
#type your code here:




 R = 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


#### (d) Your matrix $R$ should now be transformed into $rref(A)$ (since $A$ is a random $3 \times 4$ matrix, $rref(A)$ is (almost) sure to have rank (3) `np.linalg.matrix_rank(R)`. Check your answer by python with the rref method . If the answer is not the same as the current value of your $R$, go back and redo your calculations.

- use the the built in rref method `sympy.rref()`
- print the output matrix in numpy array type

    - `M = sym.Matrix(A)`
    - `M_rref = M.rref()`
    - `R = np.array((M_rref[0])).astype(np.float64)`

In [285]:
import sympy as sym
M = sym.Matrix(A)
M_rref = M.rref()
R = np.array((M_rref[0])).astype(np.float64)

rank_A=np.linalg.matrix_rank(A)
rank_R=np.linalg.matrix_rank(R)
print("rank = \n ", rank_A,"\n")
if rank_A == rank_R :
    print ("The Row echelon form of matrix M \n ",R)
else:
    print ("\n \n the rank are different")

rank = 
  3 

The Row echelon form of matrix M 
  [[  1.           0.           0.          47.        ]
 [  0.           1.           0.         -39.        ]
 [  0.           0.           1.          30.71428571]]


In [18]:
#type your code here:

# Use sympy.rref() method 



 rank = 
 3

 The Row echelon form of matrix M 
 [[ 1.          0.          0.          0.20945946]
 [ 0.          1.          0.          1.01351351]
 [ 0.          0.          1.         -0.16891892]]


# Question 5. Matrix Multiplication using Different views

we discussed in the lecture four different ways about product $AB = C$ where $A$ and $B$ are arbitry matrices. If $A$ is an $m \times n$ matrix and $B$ is an $n \times p$ matrix, then $C$ is an $m \times p$ matrix:

1. **Standard(row times column):** The standard way of describing a matrix product is to say that $c_(ij)$ equals the dot product of row $i$ of matrix $A$ and column $j$ of matrix $B$. 
 
2. **Columns:** The product of matrix $A$ and column $j$ of matrix $B$ equals column $j$ of matrix  $C$. This tells us that the columns of $C$ are combinations of columns of $A$.

3. **Rows:** The product of row $i$ of matrix $A$ and matrix $B$ equals row $i$ of matrix $C$.So the rows of $C$ are combinations of rows of $B$.

4. **Column times row**: A column of $A$ is an $m \times 1$ vector and a row of $B$ is a $1 \times p$ vector.Their product is a matrix.

In [17]:

def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistent')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))

    for i in range(m):
        for j in range(p):
            # Dot product of row i of matrix A and column j of matrix B
            C[i, j] = np.dot(A[i, :], B[:, j])

    return C

def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistent')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))

    for j in range(p):
        # Multiplying matrix A with column j of matrix B to get column j of matrix C
        C[:, j] = A @ B[:, j]

    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistent')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))

    for i in range(m):
        # Multiplying row i of matrix A with matrix B to get row i of matrix C
        C[i, :] = A[i, :] @ B

    return C




def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistent')

    m, n = A.shape
    n, p = B.shape

    C = np.zeros((m, p))

    for i in range(n):
        C+= np.dot(A[:,[i]], B[[i],:])
        
    return C

# def mat_mul_column_times_row(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistent')

#     m, n = A.shape
#     n, p = B.shape

#     C = np.zeros((m, p))

#     for i in range(m):
#         for j in range(p):
#             # Column vector from matrix A multiplied by row vector from matrix B to get matrix C
#             C[i,:] = np.dot(A[:, i], B.T)

#     return C 



# def mat_mul_column_times_row_optimized(A, B):
#     if not check_dimension(A, B):
#         raise Exception('Dimensions aren\'t consistent')

#     # Transpose matrix B for efficient column access
#     B_T = B.T

#     # Matrix C initialization
#     C = np.dot(A.T, B_T)

#     return C

In this problem we will use python to perform the matrix multiplication using these different ways, and compute the execution time for each method time.

(Write your code as a function that perform the multiplication for arbitrary size of the matrices $A$ and $B$)

In [229]:
def check_dimension(A, B):
    return A.shape[1] == B.shape[0]

def mat_mul_standard(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################        
    return C


def mat_mul_columns(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C

def mat_mul_rows(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C



def mat_mul_column_times_row(A, B):
    if not check_dimension(A, B):
        raise Exception('Dimensions aren\'t consistant')
        
    m, n = A.shape
    n, p = B.shape
            
    C = np.zeros((m, p))
    ################type your code here#####################
    

    ########################################################         
    return C

In [18]:
#A = np.array([[12., 7., 3.],[4., 5., 6.],[7., 8., 9.]])
#B = np.array([[5., 8., 1., 2.],[6., 7., 3., 0.],[4., 5., 9., 1.]])

A = np.fix((10*(np.random.rand(300, 300))))
B = np.fix((10*(np.random.rand(300, 300))))

In [19]:
%%time
print('A @ B = \n', A @ B)

A @ B = 
 [[5907. 5925. 5897. ... 6676. 6370. 6158.]
 [5779. 6057. 5900. ... 6525. 6290. 5893.]
 [5784. 6107. 6201. ... 6914. 6341. 6152.]
 ...
 [5654. 5850. 5662. ... 6572. 5951. 5615.]
 [5861. 6005. 5905. ... 6463. 5956. 5629.]
 [5702. 5904. 5878. ... 6299. 6115. 6090.]]
CPU times: total: 0 ns
Wall time: 1.99 ms


In [20]:
%%time
C_standard = mat_mul_standard(A, B)
print('C_standard = \n', C_standard)

C_standard = 
 [[5907. 5925. 5897. ... 6676. 6370. 6158.]
 [5779. 6057. 5900. ... 6525. 6290. 5893.]
 [5784. 6107. 6201. ... 6914. 6341. 6152.]
 ...
 [5654. 5850. 5662. ... 6572. 5951. 5615.]
 [5861. 6005. 5905. ... 6463. 5956. 5629.]
 [5702. 5904. 5878. ... 6299. 6115. 6090.]]
CPU times: total: 156 ms
Wall time: 162 ms


In [21]:
%%time
C_columns = mat_mul_columns(A, B)
print('C_columns = \n', C_columns)

C_columns = 
 [[5907. 5925. 5897. ... 6676. 6370. 6158.]
 [5779. 6057. 5900. ... 6525. 6290. 5893.]
 [5784. 6107. 6201. ... 6914. 6341. 6152.]
 ...
 [5654. 5850. 5662. ... 6572. 5951. 5615.]
 [5861. 6005. 5905. ... 6463. 5956. 5629.]
 [5702. 5904. 5878. ... 6299. 6115. 6090.]]
CPU times: total: 93.8 ms
Wall time: 6.7 ms


In [22]:
%%time
C_rows = mat_mul_rows(A, B)
print('C_rows = \n', C_rows)

C_rows = 
 [[5907. 5925. 5897. ... 6676. 6370. 6158.]
 [5779. 6057. 5900. ... 6525. 6290. 5893.]
 [5784. 6107. 6201. ... 6914. 6341. 6152.]
 ...
 [5654. 5850. 5662. ... 6572. 5951. 5615.]
 [5861. 6005. 5905. ... 6463. 5956. 5629.]
 [5702. 5904. 5878. ... 6299. 6115. 6090.]]
CPU times: total: 0 ns
Wall time: 5.98 ms


In [23]:
%%time
C_column_times_row = mat_mul_column_times_row(A , B)
print('C_column_times_row = \n', C_column_times_row)

C_column_times_row = 
 [[5907. 5925. 5897. ... 6676. 6370. 6158.]
 [5779. 6057. 5900. ... 6525. 6290. 5893.]
 [5784. 6107. 6201. ... 6914. 6341. 6152.]
 ...
 [5654. 5850. 5662. ... 6572. 5951. 5615.]
 [5861. 6005. 5905. ... 6463. 5956. 5629.]
 [5702. 5904. 5878. ... 6299. 6115. 6090.]]
CPU times: total: 203 ms
Wall time: 22.9 ms
